 # Варіант 14

Домашнє завдання №1

In [30]:
import numpy as np
from numpy import random

Завдання 1. Створіть одновимірний масив (вектор) зі зменшувальною геометричною послідовністю, де кожне наступне число менше попереднього в 3 рази, починаючи з 81, та виведіть його значення. 

In [127]:
a = np.flip(np.geomspace(1, 81, num=5))
print("Вектор: ", a)

Вектор:  [81. 27.  9.  3.  1.]


Завдання 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його оберненими значеннями дробових частин від ділення кожного числа на 2, починаючи з 1, та виведіть його значення. 

In [128]:
m1 = np.zeros((3, 3))
value = 1
for i in range(3):
    for j in range(3):
        m1[i, j] = 1.0 / (2 * value)
        value += 1
print("Матриця: ", m1)

Матриця:  [[0.5        0.25       0.16666667]
 [0.125      0.1        0.08333333]
 [0.07142857 0.0625     0.05555556]]


Завдання 3. Створіть масив розміром 5x5, заповніть його випадковими натуральними числами від 1 до 50 та знайдіть суму парних чисел.

In [130]:
a = np.random.randint(0, 51, (5, 5))
even = a[a % 2 == 0]
sum = np.sum(even)
print("Масив")
print(a)
print("Сума парних чисел: ", sum)  

Масив
[[48  7 36 41 15]
 [ 5  3 44 18 43]
 [48  2 24 11  8]
 [17 37 16 48 26]
 [ 7 26 38 48 16]]
Сума парних чисел:  446


Завдання 4. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть середнє арифметичне елементів, розташованих на побічній діагоналі. 

In [131]:
a = np.random.rand(5, 5)
print("Масив")
print(a)
diag = np.diag(np.flipud(a))
print("Середнє арифметичне елементів, розташованих на побічній діагоналі: ", np.average(diag))

Масив
[[0.48394683 0.45163479 0.83058963 0.30117481 0.38302435]
 [0.33378629 0.87700886 0.18155968 0.95419272 0.02296344]
 [0.124915   0.08895036 0.61977445 0.74323822 0.75667365]
 [0.21585877 0.06196251 0.64167724 0.53245854 0.2641254 ]
 [0.60817132 0.0381711  0.54255238 0.36011454 0.30695034]]
Середнє арифметичне елементів, розташованих на побічній діагоналі:  0.5254250704137633


Завдання 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення. 

In [133]:
arr1 = []
arr2 = []
arr1 = np.random.randint(1, 21, size=(5))
arr2 = np.random.randint(1, 21, size=(5))
print("Масив 1: ", arr1)
print("Масив 2: ",arr2)
addition = np.add(arr1, arr2)
print("Додавання: ", addition)
subtraction = np.subtract(arr1, arr2)
print("Віднімання: ",subtraction)
multiplication = np.multiply(arr1, arr2)
print("Множення: ", multiplication)


Масив 1:  [18  2 13 14 14]
Масив 2:  [20  3  5  8 18]
Додавання:  [38  5 18 22 32]
Віднімання:  [-2 -1  8  6 -4]
Множення:  [360   6  65 112 252]


Завдання 6. Створіть два вектори розміром 6, заповніть їх довільними дійсними числами та знайдіть їх скалярний добуток. 

In [134]:
vec1 = []
vec2 = []
vec1 = np.random.randint(1,15, size=(6))
vec2 = np.random.randint(1,15, size=(6))
scalar = np.dot(vec1, vec2)
print("Вектор 1: ", vec1)
print("Вектор 2: ",vec2)
print("Скалярний добуток: ", scalar)

Вектор 1:  [ 1 11  8  6  1 14]
Вектор 2:  [ 4  4  4  6 11  3]
Скалярний добуток:  169


Завдання 7. Створіть дві матриці розміром 2x3 та 3x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 15 та перемножте їх між собою. 

In [137]:
m1 = np.random.randint(1, 16, size=(2, 3))
m2 = np.random.randint(1, 16, size=(3, 4))
print("Матриця 1:")
print(m1)
print("Матриця 2:")
print(m2)
multiplication = np.dot(m1, m2)
print("Перемножена матриця: ")
print(multiplication)

Матриця 1:
[[ 3  9  8]
 [ 8  8 11]]
Матриця 2:
[[13 11  1  4]
 [10  1  9 14]
 [ 9 10  2 14]]
Перемножена матриця: 
[[201 122 100 250]
 [283 206 102 298]]


Завдання 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю. 

In [140]:
m1 = np.random.randint(1, 11, size=(3, 3))
reverse = np.linalg.inv(m1)
print("Матриця:")
print(m1)
print("Обернена матриця:")
print(reverse)

Матриця:
[[8 2 1]
 [5 6 1]
 [2 3 5]]
Обернена матриця:
[[ 0.15606936 -0.04046243 -0.02312139]
 [-0.13294798  0.21965318 -0.01734104]
 [ 0.01734104 -0.11560694  0.21965318]]


Завдання 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її. 

In [141]:
m1 = np.random.rand(4,4)
print("Матриця:")
print(m1)
print("Транспонована матриця:")
print(np.transpose(m1))

Матриця:
[[0.80042826 0.99411059 0.05640241 0.58925199]
 [0.13907949 0.98548257 0.08743208 0.25652557]
 [0.464861   0.10095761 0.29455861 0.15732571]
 [0.58767472 0.13462193 0.07980196 0.09604499]]
Транспонована матриця:
[[0.80042826 0.13907949 0.464861   0.58767472]
 [0.99411059 0.98548257 0.10095761 0.13462193]
 [0.05640241 0.08743208 0.29455861 0.07980196]
 [0.58925199 0.25652557 0.15732571 0.09604499]]


Завдання 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть суму додатних елементів отриманої матриці. 

In [142]:
m1 = np.random.rand(3, 4)
vec1 = np.random.rand(4)
print("Матриця:")
print(m1)
print("Вектор:")
print(vec1)
even = m1[m1 > 0]
print("Сума додатних елементів отриманої матриці: ")
print(np.sum(even))

Матриця:
[[0.35616472 0.82650138 0.29421143 0.89499693]
 [0.59775729 0.3649464  0.38081543 0.6015223 ]
 [0.19807714 0.9710223  0.06388842 0.21137119]]
Вектор:
[0.70995722 0.11075307 0.99861665 0.57691661]
Сума додатних елементів отриманої матриці: 
5.761274929883437


Завдання 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть суму елементів матриці, які менше за відповідний елемент вектору. 

In [144]:
m1 = np.random.rand(2, 3)
vec1 = np.random.randint(1, 11, size=(3))
print("Матриця: ")
print(m1)
print("Вектор:")
print(vec1)
sum = np.sum(m1[m1 < vec1])
print("Cуму елементів матриці, які менше за відповідний елемент вектору^ ")
print(sum)

Матриця: 
[[0.39948148 0.75763875 0.29981589]
 [0.39706775 0.27323061 0.69212208]]
Вектор:
[ 4  1 10]
Cуму елементів матриці, які менше за відповідний елемент вектору^ 
2.8193565584570552


Завдання 12. Створіть дві матриці розміром 7x7, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть добуток елементів другого рядка другої матриці. 

In [145]:
m1 = np.random.randint(1, 11, size=(7, 7))
m2 = np.random.randint(1, 11, size=(7, 7))
print("Матриця 1: ")
print(m1)
print("Матриця 2: ")
print(m2)
a = np.prod(m2[1, :])
print("Добуток елементів другого рядка другої матриці: ")
print(a)

Матриця 1: 
[[ 5  7  1 10  1  8  4]
 [ 4  5  2  9 10  2  1]
 [ 5  9  4  7  9  4  9]
 [ 5  4  8  5  1  2  9]
 [ 1  9  3  5  9  3  7]
 [ 6 10  8  1 10  5  3]
 [ 8  5 10  8  2 10  2]]
Матриця 2: 
[[10  4 10  6  5 10  5]
 [ 6  4  6  3  1  1  4]
 [10  3  4  2  4  3  2]
 [10  1  3  4  7  5  1]
 [ 3  8  4  6 10  4  5]
 [ 6  1  2  7 10  6  2]
 [ 3  6  8 10 10  2  9]]
Добуток елементів другого рядка другої матриці: 
1728


Завдання 13. Створіть дві матриці розміром 6x6, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть суму їх елементів. 

In [146]:
m1 = np.random.randint(-5, 6, size=(6, 6))
m2 = np.random.randint(-5, 6, size=(6, 6))
print("Матриця 1: ")
print(m1)
print("Матриця 2: ")
print(m2)
sum1 = np.sum(m1)
print("Сума елементів 1 матриці: ")
print(sum1)
sum2 = np.sum(m2)
print("Сума елементів 2 матриці: ")
print(sum2)

Матриця 1: 
[[ 1 -1  1 -4 -3 -5]
 [-4  2  2 -5 -2 -5]
 [-5  1  4  1 -1  0]
 [ 4  2  4  4  4  0]
 [ 0 -3  5 -3 -3 -5]
 [ 2  4  2 -2  5  5]]
Матриця 2: 
[[-2  2  4  0  0 -1]
 [-1 -2  3  5  2 -1]
 [-1 -4  2 -1 -5  5]
 [ 1  0  3 -4  2  5]
 [-4 -4 -3  3  2  5]
 [-3 -2  3 -5  5  1]]
Сума елементів 1 матриці: 
2
Сума елементів 2 матриці: 
10


Завдання 14. Створіть матрицю розміром 6x6, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть добуток елементів матриці, які менше за їх середнє арифметичне значення. 

In [147]:
m1 = np.random.randint(1, 101, size=(6, 6))
print("Матриця: ")
print(m1)
multiplication = np.prod(m1[m1 < np.average(m1)])
print("Добуток елементів матриці, які менше за їх середнє арифметичне значення: ")
print(multiplication)

Матриця: 
[[75 46  8  7 21 88]
 [90 41 87  7  6 14]
 [58 44 15 63 91 60]
 [84 92 73 38 91 62]
 [ 7 48 24 98 17  2]
 [20 23  1 91 14 21]]
Добуток елементів матриці, які менше за їх середнє арифметичне значення: 
1125220352


Завдання 15. Створіть матрицю розміром 8x8, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить найбільше ціле значення в кожному рядку матриці. 

In [148]:
m1 = np.random.uniform(-1, 1, size=(8, 8))
print("Матриця: ")
print(m1)
vec1 = np.max(np.abs(m1), axis=1)
print("Вектор: ")
print(vec1)

Матриця: 
[[-0.80996697  0.56913195 -0.88590075 -0.41325107  0.24747994  0.57419584
   0.01487651  0.09736816]
 [ 0.49830331 -0.95502921 -0.4252871   0.92922379  0.0835143  -0.82279204
   0.4536183   0.55995829]
 [ 0.02659486 -0.72705297 -0.61503468 -0.96226358 -0.24618736 -0.43871774
   0.78016539  0.58228691]
 [-0.1160394   0.59828197  0.09064496 -0.23458626  0.03981657 -0.34568647
   0.62779369 -0.33084805]
 [ 0.04076193 -0.21714902 -0.81112652  0.4953043   0.27373747  0.79750316
   0.27026452  0.39738212]
 [ 0.01271854  0.31827162 -0.59097878 -0.33316218 -0.74307159 -0.76219623
   0.47450432 -0.24633895]
 [-0.24531113 -0.07178329  0.40199018  0.27535115  0.9864257   0.10313869
   0.64093888 -0.47174721]
 [-0.22676915  0.30084694  0.53157755 -0.55711131 -0.71446208  0.55371107
   0.90382106 -0.01824742]]
Вектор: 
[0.88590075 0.95502921 0.96226358 0.62779369 0.81112652 0.76219623
 0.9864257  0.90382106]


Висновок: у цій практичній роботі я навчився користуватися фунціями numpy для створення масивів та матриць, виконання математичних операцій з цими масивами та матрицями, також попрацював з документацією numpy